### ISSUE TITLE
There is no such action to be used in the actions

### ISSUE THREAD

**Issue by Lemonbrush** [Bioblaze/rcedit-action#1]
I tried this action and it is failed because GitHub actions cannot find it. This tool would be really handy for me though

**Comment by Bioblaze** [comment]
ok i put it on the marketplace for you @Lemonbrush https://github.com/marketplace/actions/set-resources-on-files-with-rcedit

**Comment by Bioblaze** [comment]
If you need anything, make a new ticket <3 thank you for your usage.
